//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLD521SA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paper
    {
        [Key]
        public int PaperId { get; set; }
        [Required(ErrorMessage = "The Title field is required.")]
        public string PaperTitle { get; set; }
        [Required(ErrorMessage = "The Abstract field is required.")]
        [DataType(DataType.MultilineText)]
        public string PaperAbstract { get; set; }
        [Required]
        public string PaperAuthor { get; set; }
        [Required]
        public System.DateTime PaperDateSubmitted { get; set; }
        [Required(ErrorMessage = "The value '' is invalid.")]
        public int TopicId { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
